import type { Metadata } from "next";
import "./globals.css";
import NextUIProviders from "@/components/providers/NextUIProviders";
import TopNav from "@/components/navbar/TopNav";

export const metadata: Metadata = {
   title: "Next-Macth",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body>
            <NextUIProviders>
               <TopNav />
               <main className="mx-auto container p-10">{children}</main>
            </NextUIProviders>
         </body>
      </html>
   );
}
